object ThirdParty {
    const val dialog_version = "3.3.0"
    const val retrofit_version = "2.6.2"
    const val glide_version = "4.9.0"
    const val mmkv = "com.tencent:mmkv:1.0.22"
    const val loadsir = "com.kingja.loadsir:loadsir:1.3.6"
    const val dialogslifecycle = "com.afollestad.material-dialogs:lifecycle:$dialog_version"
    const val dialogscore = "com.afollestad.material-dialogs:core:$dialog_version"
    const val dialogscolor = "com.afollestad.material-dialogs:color:$dialog_version"
    const val dialogsdatetime = "com.afollestad.material-dialogs:datetime:$dialog_version"
    const val dialogsbottomsheets = "com.afollestad.material-dialogs:bottomsheets:$dialog_version"
    const val photoselect = "com.yuyh.imgsel:library:2.1.0"
    const val bannerViewPager = "com.github.zhpanvip:BannerViewPager:2.6.6"
    const val magicIndicator = "com.github.hackware1993:MagicIndicator:1.6.0"
    const val recyclerview = "com.yanzhenjie.recyclerview:x:1.3.2"
    const val baseRecyclerViewAdapterHelper =
        "com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.4"
    const val refreshLayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
    const val swithView = "ch.ielse:switchbutton:1.0.0"
    const val rxpermission = "com.github.tbruyelle:rxpermissions:0.10.2"
    const val picview = "com.contrarywind:Android-PickerView:4.1.9"
    const val ratingbar = "com.github.giswangsj:AndRatingBar:1.0.4"
    const val arscan = "com.github.bingoogolapple.BGAQRCode-Android:zbar:1.3.8"
    const val zXing = "com.github.bingoogolapple.BGAQRCode-Android:zxing:1.3.8"
    const val jpush = "cn.jiguang.sdk:jpush:3.8.6"
    const val jcore = "cn.jiguang.sdk:jcore:2.6.0"
    const val dmap = "com.amap.api:3dmap:7.8.0"
    const val location = "com.amap.api:location:latest.integration"
    const val search = "com.amap.api:search:latest.integration"
    const val wechat = "com.tencent.mm.opensdk:wechat-sdk-android-without-mta:+"
    const val bugly = "com.tencent.bugly:crashreport:latest.release"
    const val printer = "com.github.zhuhuitao:printer:1.0.9"

    const val retrofit2 = "com.squareup.retrofit2:retrofit:$retrofit_version"
    const val gson = "com.squareup.retrofit2:converter-gson:$retrofit_version"
    const val persistentcookiejar = "com.github.franmontiel:PersistentCookieJar:v1.0.1"
    const val glide = "com.github.bumptech.glide:glide:$glide_version"
    const val glidecompiler = "com.github.bumptech.glide:compiler:$glide_version"
    const val oss = "com.aliyun.dpa:oss-android-sdk:2.9.1"
    const val luban = "top.zibin:Luban:1.1.8"
    const val autoService = "com.google.auto.service:auto-service:1.0-rc7"
}